flynx/__init__.py
from setuptools.command import easy_install
from time import time 
import os, subprocess, sys

def create_app(config_filename, frontend=True):
  from flask import Flask, app, session, redirect, url_for, escape, request
  from flask.ext.bootstrap import Bootstrap
  from flask.ext.bcrypt import Bcrypt
  from werkzeug.contrib.fixers import ProxyFix
  from flynx.model import db
  import flynx.views
  
  # initiate app
  app = Flask(__name__)
  # proxy-fix for ssl-offloads, fixes bogus http-redirects
  app.wsgi_app = ProxyFix(app.wsgi_app)
  
  # add bcrypt
  app.bcrypt = Bcrypt(app)
  
  # load config
  if config_filename != "":
    app.config.from_pyfile(config_filename)
    
  # init db
  db.init_app(app)

  if frontend:
    print "> app_start"
  
    # add bootstrap css/js
    flynx.bootstrap = Bootstrap(app)
    app.register_blueprint(flynx.views.default, template_folder='templates')
    app.register_blueprint(flynx.views.groups, template_folder='templates')
    app.register_blueprint(flynx.views.nodes, template_folder='templates')
    
  ## end frontend
  
  # TODO: make app_start/seed
  @app.before_request
  def _render_less_css():
      static_dir = app.static_folder
      
      less_paths = []
      
      for path, subdirs, filenames in os.walk(static_dir):       
          less_paths.extend([
              os.path.join(path, f)
              for f in filenames if os.path.splitext(f)[1] == '.less'
              
              
          ])
      for less_path in less_paths:
          css_path = os.path.splitext(less_path)[0] + '.css'
          if not os.path.isfile(css_path):
              css_mtime = -1
          else:
              css_mtime = os.path.getmtime(css_path)
          less_mtime = os.path.getmtime(less_path)
          if less_mtime >= css_mtime:
              app.logger.debug("recompiled "+less_path)
              subprocess.call(['lessc', less_path], stdout=open(css_path, "w"), shell=False)
  
  
  return app

def install():
  for dep in dependencies():
    install_dependency(dep)
    
def install_dependency(dependency):
  easy_install.main([dependency])
  
def reset_database(flaskcfg, cfg):
  from alembic.config import Config
  from alembic import command
  alembic_cfg = Config(cfg)
  command.downgrade(alembic_cfg, "base")
  command.upgrade(alembic_cfg, "head")
  
  return seed_database(flaskcfg)

def seed_database(config_filename):
  app = create_app(config_filename, False)
  
  from sqlalchemy.exc import IntegrityError
  from flynx.model import User, Node, Group
  from flynx.model import db
  
  app.test_request_context().push()
  
  node = Node("localhost", "flynx", 8081)
  
  db.session.add(User("admin@example.com", "hunter2"))
  db.session.add(node)
  db.session.add(Group("test_group", [node]))
  
  try:
    db.session.commit()
  except IntegrityError:
    print "already seeded"
    
def database_shell(config_filename):
  app = create_app(config_filename, False)
  import flynx.model
  from flynx.model import db
  
  app.test_request_context().push()

  import code
  import readline
  import rlcompleter

  vars = globals()
  vars.update(locals())
  readline.set_completer(rlcompleter.Completer(vars).complete)
  readline.parse_and_bind("tab: complete")
  shell = code.InteractiveConsole(vars)
  shell.interact()
  
  
def dependencies():
  return [
    'flask',
    'flask-bootstrap',
    'flask-sqlalchemy',
    'flask-login',
    'flask-bcrypt',
    'flask-wtf',
    'psycopg2',
    'requests',
    'alembic'
  ]

flynx/model/__init__.py
from flask.ext.sqlalchemy import SQLAlchemy
db = SQLAlchemy()

from renderable import Renderable
from node_history import NodeHistory
from node import Node
from group import Group
from user import User
from node_create_validator import NodeCreateValidator
from node_update_validator import NodeUpdateValidator
__all__ = [
  "Node",
  "NodeHistory",
  "Group",
  "Renderable",
  "User",
  "NodeCreateValidator",
  "NodeUpdateValidator"
]

flynx/request/__init__.py
from query import Query
from query_error import QueryError

flynx/views/__init__.py
from flask import current_app, redirect, url_for, flash, session, request, Response
from functools import wraps
from flynx.model import User

def authenticate():
   """Sends a 401 response that enables basic auth"""
   return Response(
   'Please Login', 401,
   {'WWW-Authenticate': 'Basic realm="Login"'})

def requires_auth(f):
   @wraps(f)
   def decorated(*args, **kwargs):

       auth = request.authorization
       if not auth or not check_login(auth.username, auth.password):
           return authenticate()

       try:
           sess = request.cookies.get('dxid').encode("utf-8")
       except:
           flash('Your sessions seems to have expired, creating new')
           sess = "invalid"

       return f(*args, **kwargs)
   return decorated


def check_login(user, pw):
  u = User.query.filter_by(email=user).first()
  
  return u and u.check_password(pw)
  
from default import default
from groups import groups
from nodes import nodes

__all__ = [ 'default', 'groups', 'nodes' ]

flynx/views/default.py
from flask import current_app, Blueprint, render_template, abort, request, redirect, url_for
from flynx.views import requires_auth

default = Blueprint('default', __name__, url_prefix = '/')

@default.route("/")
@requires_auth
def index():
  return render_template("default/index.html")

flynx/views/groups.py
from flask import current_app, Blueprint, render_template, abort, request, redirect, url_for
from flynx.views import requires_auth
from flynx.model import Group, Node
from flask.json import jsonify

groups = Blueprint('groups', __name__, url_prefix = '/groups')

@groups.route("/")
@requires_auth
def index():
  return render_template("groups/index.html")
  
@groups.route(".json")
@requires_auth
def index_json():
  groups = Group.query.all()
  
  result = map(lambda g: g.to_json(), groups)
  return jsonify(data=result)

flynx/views/nodes.py
from flask import current_app, Blueprint, render_template, abort, request, redirect, url_for
from flask.json import jsonify
from flynx.views import requires_auth
from flynx.model import Node, NodeCreateValidator, NodeUpdateValidator

nodes = Blueprint('nodes', __name__, url_prefix = '/nodes')

@nodes.route("/")
@requires_auth
def index():
  return render_template("nodes/index.html")
  
@nodes.route(".json")
@requires_auth
def index_json():
  if request.method == "GET":
    nodes = Node.query.all()
  
    result = map(lambda n : n.to_tree(), nodes)
    return jsonify(data=result)
  
  if request.method == "POST":
    validator = NodeCreateValidator(request.get_json(silent=True))
    result = validator.commit()
    
    if result:
      return jsonify(data=result)
    else:
      return abort(500)
      
  
@nodes.route("/<int:id>.json", methods=["GET", "PUT"])
def show_json(id):
  if request.method == "GET":
    node = Node.query.get(id)
  
    if node:
      result = node.to_tree()
      return jsonify(data=result)
  
    return abort(404)
  if request.method == "PUT":  
    validator = NodeUpdateValidator(request.get_json(silent=True))
    result = validator.commit()
    
    if result:
      return jsonify(data=result)
    else:
      return abort(500)

flynx/templates/default/index.html
{% extends "layouts/application.html" %}
{% block container %}
{% endblock %}

flynx/templates/groups/index.html
{% extends "layouts/application.html" %}

{% block container %}
  <div class="row">
    <div class="col-md-6" ng-controller="GroupsController">
      <h3>Groups</h3>
      <div id="js-node-tree"/>
    </div>    
  </div>
{% endblock %}

flynx/templates/layouts/_alerts.html
{% with errors = get_flashed_messages(category_filter=["error"]) %}
{% if errors %}
<div class="alert alert-danger">
  <ul>
    {%- for msg in errors %}
    <li>{{ msg }}</li>
    {% endfor -%}
  </ul>
</div>
{% endif %}
{% endwith %}
{% with success = get_flashed_messages(category_filter=["success"]) %}
{% if success %}
<div class="alert alert-success">
  <ul>
    {%- for msg in success %}
    <li>{{ msg }}</li>
    {% endfor -%}
  </ul>
</div>
{% endif %}
{% endwith %}

{% with infos = get_flashed_messages(category_filter=["info"]) %}
{% if infos %}
<div class="alert alert-info">
  <ul>
    {%- for msg in infos %}
    <li>{{ msg }}</li>
    {% endfor -%}
  </ul>
</div>
{% endif %}
{% endwith %}

flynx/templates/layouts/_nav.html
{% block nav_main_content %}
  <ul class="nav navbar-nav">
    <li>
      <a href="{{ url_for('groups.index') }}">Groups</a>
    </li>
    <li>
      <a href="{{ url_for('nodes.index') }}">Single Nodes</a>
    </li>
  </ul>
{% endblock nav_main_content %}

flynx/templates/layouts/application.html
{% extends "bootstrap/base.html" %}
{% block title %}Flynx{% endblock %}

{% block scripts %}
  <script type="text/javascript" src="{{ url_for('static', filename='core/javascripts/application.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='jstree/jstree.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='angular.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='script.js') }}"></script>
{% endblock %}


{% block styles %}
  <link href="{{ url_for('static', filename='core/stylesheets/application.css') }}" rel="stylesheet" media="screen"/>
  <link href="{{ url_for('static', filename='style.css') }}" rel="stylesheet" media="screen"/>
  <link href="{{ url_for('static', filename='glyph.css') }}" rel="stylesheet" media="screen"/>
  <link href="{{ url_for('static', filename='jstree/themes/default/style.css') }}" rel="stylesheet" media="screen"/>
{% endblock %}



{% block navbar %}


    
    


 <nav class="navbar navbar-default navbar-inverse navbar-static-top" role="navigation"> 
 <!-- Brand and toggle get grouped for better mobile display --> 
 <div class="navbar-header"> 
  <a class="navbar-brand" href="/">Flynx - Upstream Management</a> 
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-primary"> 
    <span class="sr-only">Side Navigation</span> 
    <i class="icon-th-list"></i> 
  </button> 
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse-top"> 
    <span class="sr-only">Top Navigation</span> 
    <i class="icon-align-justify"></i> 
  </button> 
 </div> <!-- Collect the nav links, forms, and other content for toggling --> 
 <div class="collapse navbar-collapse navbar-collapse-top"> 


    {% block nav_content %}
      {% include "layouts/_nav.html" %}    
    {% endblock nav_content %}
 </div> 
 </nav><!-- /.navbar-collapse -->
 
     {% block sidebar_content %}
    {% endblock %}

{% endblock %}

{% block content %}

<div class="main-content" ng-app="flynx">
  <div class="container">

    {% include "layouts/_alerts.html" %}    
    
        {% block container %}
        {% endblock container %}

  </div>
</div>
{% endblock content %}

flynx/templates/nodes/index.html
{% extends "layouts/application.html" %}

{% block container %}
  <div ng-controller="NodesController">
    <div class="row margin-bottom-md">
      <div class="col-md-5">
        <h3>Nodes <a href="#" class="btn glyph glyph-refresh" ng-click="tree.refresh()"></a></h3>
        <div id="js-node-tree"></div>
      </div>
    </div>
    <div class="row margin-bottom-md">    
      <div class="col-md-5">
        <a href="#" class="btn btn-green" ng-click="tree.up()">Up</a>
        <a href="#" class="btn btn-red" ng-click="tree.down()">Down</a>
      </div>
    </div>
  </div>
{% endblock %}